import Head from "next/head";
import { Inter } from "next/font/google";
import Navbar from "@/components/navbar";

const inter = Inter({ subsets: ["latin"] });

export default function IndustryBasedSupervisor() {
  return (
    <>
      <Head>
        <title>E LogBook - Industry-Based Supervisor</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.png" />
      </Head>

      <main className={inter.className}>
        <Navbar />
        Industry-Based Supervisor
      </main>
    </>
  );
}
